# Generated by Django 5.1 on 2024-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_alter_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
    ]
